@startuml zustandsdiagramm
[*] --> Index
Index: Token vorhanden

state "/login" as auth {
    Anmeldeformular: Benutzername
    Anmeldeformular: Passwort
    state Anmeldergebnis <<choice>>

    [*] --> Anmeldeformular
    Anmeldeformular --> Anmeldergebnis
    Anmeldergebnis --> AnmeldeFehler: Fehlerhafte Daten
    Anmeldergebnis --> BackendFehlerAuth: Backend nicht erreichbar
    Anmeldergebnis --> Index: Erfolg (authorisiert)
}

state "/create" as create {
    Anlegeformular: Formulardaten
    state Anlegeergebnis <<choice>>

    [*] --> Anlegeformular
    Anlegeformular --> Anlegeergebnis
    Anlegeergebnis --> AnlegeFehler: Fehlerhafte Daten
    Anlegeergebnis --> BackendFehlerCreate: Backend nicht erreichbar
    Anlegeergebnis --> BookDetails: Buch erfolgreich erstellt! 
}

state "/change" as change {
    Änderungsformular: Formulardaten
    state ÄnderungsErgebnis <<choice>>

    [*] --> Änderungsformular
    Änderungsformular --> ÄnderungsErgebnis
    ÄnderungsErgebnis --> ÄnderungsFehler: Fehlerhafte Daten
    ÄnderungsErgebnis --> BackendFehlerChange: Backend nicht erreichbar
    ÄnderungsErgebnis --> BookDetails: Buch erfolgreich geändert!
}

state "/search" as search {
    Suchformular: Suchkriterien
    state Suchergebnis <<choice>>

    [*] --> Suchformular
    Suchformular --> Suchergebnis
    Suchergebnis --> KeineBuecher: Keine Bücher gefunden
    Suchergebnis --> BackendFehlerSearch: Backend nicht erreichbar
    Suchergebnis --> GefundeneBuecher: Mindestens ein Buch gefunden
}

state "/BookDetails" as success {
}

Index --> auth: Button "Login"
Index --> Index: Button "Logout" (authorisiert)
Index --> create: Menüpunkt "Anlegen" (authorisiert)
Index --> change: Menüpunkt "Ändern" (authorisiert)
Index --> search: Menüpunkt "Suche"

@enduml