import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Grid, GridItem } from '@chakra-ui/react';
import { Button, ButtonGroup } from '@chakra-ui/react';
import { Stack } from "@chakra-ui/react";
import { Providers } from "./providers";
import NextLink from 'next/link'
import { LinkButton } from "../../components/link-button";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Providers>
      <Grid
        templateAreas={`"header header"
                        "nav main"
                        "footer footer"`}
        gridTemplateRows={'80px 1fr 50px'}
        gridTemplateColumns={'120px 1fr'}
        h='1000px'
        gap='1'
        color='blackAlpha.700'
        fontWeight='bold'
      >
        <GridItem pl='2' bg='orange.300' area={'header'}>
        <Stack direction='row' spacing={4} align='center'>
            <LinkButton link='/suchen' text='Suchen' />
            <LinkButton link='/erstellen' text='Erstellen' />
            <LinkButton link='/login' text='Login' />
          </Stack>
        </GridItem>
        <GridItem pl='2' bg='pink.300' area={'nav'}> 
        </GridItem>
        <GridItem pl='2' bg='green.300' area={'main'}>
          {children}
        </GridItem>
        <GridItem pl='2' bg='blue.300' area={'footer'}>
          Footer
        </GridItem>
      </Grid>
      </Providers>
      </body>
    </html>
  );
}
